// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIJzTbiZjY7GcgMcO6fghL6IXOa_Q1lE',
    appId: '1:620637758587:web:e464783eedd25ebbc0eede',
    messagingSenderId: '620637758587',
    projectId: 'ecomapp-5181e',
    authDomain: 'ecomapp-5181e.firebaseapp.com',
    storageBucket: 'ecomapp-5181e.firebasestorage.app',
    measurementId: 'G-0GC8MLNN7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZO0ILEoz_lmp2A3gMGY0IwLjJ4qbUorc',
    appId: '1:620637758587:android:f82dff7347c3c567c0eede',
    messagingSenderId: '620637758587',
    projectId: 'ecomapp-5181e',
    storageBucket: 'ecomapp-5181e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkyhv3OBZYEkFdo3NPh-PSNOx1cBNRAw',
    appId: '1:620637758587:ios:a64fd88d9a4b0decc0eede',
    messagingSenderId: '620637758587',
    projectId: 'ecomapp-5181e',
    storageBucket: 'ecomapp-5181e.firebasestorage.app',
    iosBundleId: 'com.example.l',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkyhv3OBZYEkFdo3NPh-PSNOx1cBNRAw',
    appId: '1:620637758587:ios:a64fd88d9a4b0decc0eede',
    messagingSenderId: '620637758587',
    projectId: 'ecomapp-5181e',
    storageBucket: 'ecomapp-5181e.firebasestorage.app',
    iosBundleId: 'com.example.l',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIJzTbiZjY7GcgMcO6fghL6IXOa_Q1lE',
    appId: '1:620637758587:web:630d220d903c64c0c0eede',
    messagingSenderId: '620637758587',
    projectId: 'ecomapp-5181e',
    authDomain: 'ecomapp-5181e.firebaseapp.com',
    storageBucket: 'ecomapp-5181e.firebasestorage.app',
    measurementId: 'G-M49D8H80D1',
  );

}